[package]
name = "waxenc"
version = "1.3.1"
edition = "2021"

[profile.release]
lto = true
strip = true
codegen-units = 1

[dependencies]
bincode = "1.3.3"
native-windows-gui = "1.0.12"
sodiumoxide = "0.2.7"
serde = { version = "1.0.216", features = ["derive"] }